services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_CONFIG_FILE=/config/rabbitmq
    volumes:
      - ./config/rabbit:/config/