# @TODO: Invalidate ANY / ALL creds
spring:
  application:
    name: auth
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 996208298744-in3qbmgh9b9bh1d1ffofcia3ot29ra6o.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "${ibento.baseurl}/login/oauth2/code/google"
ibento:
  authn:
    session:
        timeout: 1800
  baseurl: http://localhost:7001
server:
  port: 7001